### ISSUE TITLE
MGN12 Version?

### ISSUE THREAD

**Issue by Killajoedotcom** [TorxFighter/Voron-Mods#1]
Do you have, or are you willing to make, an MGN12H version?

**Comment by TorxFighter** [comment]
Hello I'm assuming you are talking about the zero offset ge5c thing i made. Due to how much further the Mgn12H sticks out from the extrusion compared to Mgn9, unless you can push the mounting holes and Z belt position on the Y extrusions, it won't be possible without making significant changes.

![Udklip](https://github.com/TorxFighter/Voron-Mods/assets/58269052/1fdeaf04-7d32-4d7d-a685-a1a8c599ffc1)

**Comment by Killajoedotcom** [comment]
I think I understand what you mean. I was considering it only being wider, not thicker
